server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: heritage-hunters
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  thymeleaf:
    cache: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            redirect-uri: ${oauth.google.redirect-uri-base}/login/oauth2/code/google
            scope: profile, email
          github:
            client-id: ${oauth.github.client-id}
            client-secret: ${oauth.github.client-secret}
            redirect-uri: ${oauth.github.redirect-uri-base}/login/oauth2/code/github
            scope: user:email
          naver:
            client-id: ${oauth.naver.client-id}
            client-secret: ${oauth.naver.client-secret}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: ${oauth.naver.redirect-uri-base}/login/oauth2/code/naver
            scope:
              - name
              - email
              - profileImage
            provider: naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

logging:
  level:
    org.springframework: INFO
    org.hh.heritagehunters: INFO

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
    redirect-uri-base: ${OAUTH_GOOGLE_REDIRECT_URI_BASE}
  github:
    client-id: ${OAUTH_GITHUB_CLIENT_ID}
    client-secret: ${OAUTH_GITHUB_CLIENT_SECRET}
    redirect-uri-base: ${OAUTH_GITHUB_REDIRECT_URI_BASE}
  naver:
    client-id: ${OAUTH_NAVER_CLIENT_ID}
    client-secret: ${OAUTH_NAVER_CLIENT_SECRET}
    redirect-uri-base: ${OAUTH_NAVER_REDIRECT_URI_BASE}

google:
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: ${AWS_S3_BUCKET}

ai:
  clients:
    "1": ${AI_CLIENTS_1}
    "2": ${AI_CLIENTS_2}
    "3": ${AI_CLIENTS_3}