spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 시 테이블 자동 수정
    show-sql: true

# 로그
logging:
  level:
    org.hibernate.SQL: INFO
    org.hh.heritagehunters: DEBUG

  # Google OAuth
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: ${GOOGLE_SCOPE}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
