server:
  port: 8080

spring:
  profiles:
    active: local

  # secrets/application-secret.yml 파일을 선택적으로 불러오기
  config:
    import: optional:classpath:/secrets/application-secret.yml

  # 파일 업로드 용량 제한
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  # DB 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Spring Data JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
      encoding: UTF-8

  # thymeleaf
  thymeleaf:
    cache: false  # 개발 시 템플릿 캐시 비활성화
    mode: HTML  # 타임리프 모드 설정
    encoding: UTF-8  # 인코딩 설정

# 로그 레벨 설정
logging:
  level:
    org.springframework: INFO
    org.hh.heritagehunters: DEBUG  # 패키지 이름 기준

springdoc:
  api-docs:
    path: /v3/api-docs  # OpenAPI 스펙 접속 엔드포인트
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI 접속 엔드포인트
    disable-swagger-default-url: true  # 기본적으로 swagger-ui URL을 직접 노출하지 않도록 설정