spring:

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 시 테이블 자동 수정
    show-sql: true

  # Google OAuth
  security:
    user:
      name: admin
      password: 1234

    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.client-id}
            client-secret: ${oauth.google.client-secret}
            redirect-uri: ${oauth.google.redirect-uri-base}/login/oauth2/code/google
            scope: ${oauth.google.scope}
          github:
            client-id: ${oauth.github.client-id}
            client-secret: ${oauth.github.client-secret}
            scope: user:email
            redirect-uri: ${oauth.github.redirect-uri-base}/login/oauth2/code/github

# 로그
logging:
  level:
    org.hibernate.SQL: INFO
    org.hh.heritagehunters: DEBUG
    org.springframework.core.env: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG